# -*- coding: utf-8 -*-
"""Copy of 21107054(assignment 2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X9BUqJ2pio31qzhpX8HRmt3vQdFRK9YG
"""

#question 1

string = 'Python is a case sensitive language'

#a length of string
print("(a)length of the string :",len(string))

#b reversing the string
print("(b)",string[::-1])

#c slicing
print("(c)",string[10:26])

#d replace
new_string = string[:10]+' an object oriented '+ string[26:]
print("(d)",new_string)

#e index of a 
print("(e)index of a :",string.find('a'))

#f removing spaces 
print("(f)",string.replace(' ',''))

#Question 2

SID=21107054
name=" Ayush Srishti"
department="Mechanical"
CGPA= 9.0

print("Hey," + name + " Here!")
print("My SID is %d" %SID )
print("I am from " + department + " department and my CGPA is ", CGPA)

#Question 3

a = 56
b = 10

# (a)bitwise AND
print("(a)a&b=",a&b)

# (b) bitwise OR
print("(b)a|b=",a|b)

# (c) bitwise XOR
print("(c)a^b",a^b)

# (d) Left Shift
print("(d)a << 2 : ", a << 2, " and b << 2: ", b << 2)

# (e) Right Shift
print("(e)a >> 2 :", a >> 2," and b >> 4:", b>> 4)

# Question 4 

user_input = input("Enter input:")
if 'name' in user_input:
    print("yes")

else:
    print("no")

# Question 5

# user input 
side_1 = int(input("enter first side of triangle :"))
side_2 = int(input("enter second side of triangle :"))
side_3 = int(input("enter third side of triangle :"))

a = side_1 + side_2
b = side_2 + side_3
c = side_3 + side_1

x = (side_1 < b)
y = (side_2 < c)
z = (side_3 < a)

answer = str(x & y & z)
answer = answer.replace("True", "Yes")
answer = answer.replace("False", "No")

print(answer)

#question 6 

# user input 
a = int(input("Enter 1st no.:"))
b = int(input("Enter 2nd no.:"))

# using binary XOR and convert to string 2 
print((str(bin(a ^ b))).count('1'))